#!/usr/bin/env bash
#
# Assembles everything a designer needs to redo the download page.
#
#   tools/design-kit.sh
#
# Produces dist/netspeed-design-kit/ and a zip of it. Nothing in here is
# generated by hand: the preview carries the values of the current release and
# the icons are rendered from the same code the app ships, so the kit cannot
# show something that does not exist.
set -euo pipefail
cd "$(dirname "$0")/.."

KIT="dist/netspeed-design-kit"

rm -rf "$KIT" "$KIT.zip"
mkdir -p "$KIT/screenshots" "$KIT/icon" "$KIT/assets"

# The template, with its brief and placeholders intact — this is the file to
# edit and the file to hand back.
cp tools/page.html "$KIT/page.html"

# The same page with real values, for opening in a browser to see where things
# stand today.
NS_DRY_RUN=1 tools/publish.sh >/dev/null
cp dist/index.html "$KIT/preview.html"

cp preview/*.png "$KIT/screenshots/"

# Icons come from the app's own drawing code rather than an export someone made
# once: a redesign that wants the mark at another size gets it exact.
if [[ ! -d dist/AppIcon.iconset ]]; then
    swift tools/make-icon.swift >/dev/null
fi
cp dist/AppIcon.iconset/icon_512x512@2x.png "$KIT/icon/icon-1024.png"
cp dist/AppIcon.iconset/icon_256x256.png "$KIT/icon/icon-256.png"
cp dist/AppIcon.iconset/icon_32x32.png "$KIT/icon/icon-32.png"

cp tools/page-assets/README.md "$KIT/assets/README.md"

# Copied verbatim: the brief documents the placeholders, so substituting into
# it would rewrite the very table explaining what they are. Real values live in
# preview.html, which is what they are for.
cp tools/design-brief.md "$KIT/README.md"

(cd dist && zip -qr "netspeed-design-kit.zip" "netspeed-design-kit")

echo "-- $KIT"
find "$KIT" -type f | sed "s|$KIT/|   |" | sort
echo "-- $KIT.zip ($(du -h "$KIT.zip" | cut -f1))"
